Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'api/auth'

  namespace :api do
    post 'feedback', to: 'feedbacks#new'
    post 'uploads', to: 'uploads#file_upload'
    post 'create-test', to: 'tests#new'
    get 'user-tests', to: 'tests#user_tests'
    get 'teacher-tests', to: 'tests#teacher_tests'
    get 'check_test_variants_mode/:id', to: 'tests#test_variants_mode'
    get 'check-test/:test_id/:user_id', to: 'tests#test_get_completed'
    post 'user-test/complete/:id', to: 'tests#test_complete'
    delete 'tests/:id', to: 'tests#destroy'
    patch 'test-rate/:test_id/:user_id', to: 'tests#test_set_rate'
    patch 'test-visibility/:id', to: 'tests#test_visibility'
    post 'user-test/:id', to: 'tests#user_test'
    post 'new-group', to: 'groups#create'
    patch 'update-group', to: 'groups#update'
    get 'get-key', to: 'groups#get_key'
    get 'reset-key', to: 'groups#reset_key'
    post 'add-teacher', to: 'groups#add_teacher'
    delete 'group_subjects/:group_id/:subject_id', to: 'groups#remove_subject'
    get 'groups', to: 'groups#index'
    get 'group', to: 'groups#get_group'
    delete 'groups/:id', to: 'groups#destroy'
    patch 'groups/:id', to: 'groups#add_subject'
    delete 'students/:id', to: 'students#destroy'
    delete 'teachers/:id', to: 'teachers#destroy'
    get 'teachers', to: 'teachers#index'
    get 'subjects', to: 'subjects#index'
    post 'subjects', to: 'subjects#create'
    delete 'subjects/:id', to: 'subjects#destroy'
    patch 'profiles', to: 'profiles#update'
  end
end
